name: FlixPrimeTV metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  flixprime-organization-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV Organization
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/flixprime.svg
          user: FlixPrime-TV
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://lecoq.io
