name: FlixPrimeTV metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  flixprime-organization-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV Organization
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/flixprime.svg
          user: FlixPrime-TV
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://lecoq.io
  flixprime-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV FlixPrime.tv repo
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: metrics.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
