name: FlixPrimeTV metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  flixprime-organization-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV Organization
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/metrics/flixprimetv.metrics.svg
          user: FlixPrime-TV
          base: header
          config_display: columns
          config_order: base.header, introduction, habits, people, pagespeed
          plugin_lines: yes
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
          plugin_people: yes
          plugin_people_types: members,followers
          #plugin_people_thanks: ,thanks
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://flixprime.tv
  flixprime-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV FlixPrime.tv Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: profile/metrics/repositories/flixprime.tv.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
  flixprime-faily-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV FailyFlixPrime Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: profile/metrics/repositories/faily.flixprime.tv.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: faily.flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
  flixprime-click-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV ClickFlixPrime Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: profile/metrics/repositories/click.flixprime.tv.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: click.flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
  flixprime-soz-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV SOZFlixPrime Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: profile/metrics/repositories/soz.flixprime.tv.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: soz.flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
  flixprime-api-flixprime-tv-repo:
    runs-on: ubuntu-latest
    steps:
      - name: FlixPrimeTV FlixPrime API Repository Metrics
        uses: lowlighter/metrics@latest
        with:
          template: repository
          config_display: regular
          filename: profile/metrics/repositories/api.flixprime.tv.metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: FlixPrime-TV
          repo: api.flixprime.tv
          plugin_lines: yes
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4